### ISSUE TITLE
fix getSourceVip

### ISSUE THREAD

**Issue by jayunit100** [FriedrichWilken/KubernetesOnWindows#1] opened 2021-04-13 17:17 UTC
evidently ross @rancher has a fix to the host ip issues

**Comment by jayunit100** [comment] 2021-04-13 17:19
https://gist.github.com/rosskirkpat/063416fdf5512adc99fab85a411f7947

**Comment by sladyn98** [comment] 2021-04-16 19:09
@FriedrichWilken Would we want to get this into the powershell script to see if it works or are we going down another route with this ?

**Comment by FriedrichWilken** [comment] 2021-04-17 00:32
@sladyn98 well, the k.ps1 causes two errors 
```
Cannot index into a null array.
At C:\k\helper.psm1:179 char:5
+     $subnet = $hnsNetwork.Subnets[0].AddressPrefix
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

4
5
You cannot call a method on a null-valued expression.
At C:\sync\k.ps1:191 char:1
+ $sourceVip = $sourceVipJSON.ip4.ip.Split("/")[0]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
Where the second seems to be caused by the first one. The first one points at `C:\k\helper.psm`
in this file at the is this function that seems to be the problem.
```
function GetSourceVip($ipaddress, $NetworkName)
{
    $hnsNetwork = Get-HnsNetwork | ? Name -EQ $NetworkName.ToLower()
    $subnet = $hnsNetwork.Subnets[0].AddressPrefix

    $ipamConfig = @"
        {"cniVersion": "0.2.0", "name": "vxlan0", "ipam":{"type":"host-local","ranges":[[{"subnet":"$subnet"}]],"dataDir":"/var/lib/cni/networks"}}
"@

    $ipamConfig | Out-File "C:\k\sourceVipRequest.json"

    $env:CNI_COMMAND="ADD"
    $env:CNI_CONTAINERID="dummy"
    $env:CNI_NETNS="dummy"
    $env:CNI_IFNAME="dummy"
    $env:CNI_PATH="c:\k\cni" #path to host-local.exe

    If(!(Test-Path c:/k/sourceVip.json)){
        Get-Content sourceVipRequest.json | .\cni\host-local.exe | Out-File sourceVip.json
    }

    Remove-Item env:CNI_COMMAND
    Remove-Item env:CNI_CONTAINERID
    Remove-Item env:CNI_NETNS
    Remove-Item env:CNI_IFNAME
    Remove-Item env:CNI_PATH
}
```
So I would suggest that we throw a copy of the file @jayunit100 shared (without the `Invoke-WebRequest ...`) into the `./Win` dir and call it in `k.ps1` instead of 
```
GetSourceVip -ipAddress 10.0.0.10 -NetworkName $NetworkName
```

**Comment by FriedrichWilken** [comment] 2021-04-17 11:47
> @sladyn98 well, the k.ps1 causes two errors
> 
> ```
> Cannot index into a null array.
> At C:\k\helper.psm1:179 char:5
> +     $subnet = $hnsNetwork.Subnets[0].AddressPrefix
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : NullArray
> 
> 4
> 5
> You cannot call a method on a null-valued expression.
> At C:\sync\k.ps1:191 char:1
> + $sourceVip = $sourceVipJSON.ip4.ip.Split("/")[0]
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : InvokeMethodOnNull
> ```
> 
> Where the second seems to be caused by the first one. The first one points at `C:\k\helper.psm1`.
> In `helper.psm1` this function is causing the error:
> 
> ```
> function GetSourceVip($ipaddress, $NetworkName)
> {
>     $hnsNetwork = Get-HnsNetwork | ? Name -EQ $NetworkName.ToLower()
>     $subnet = $hnsNetwork.Subnets[0].AddressPrefix
> 
>     $ipamConfig = @"
>         {"cniVersion": "0.2.0", "name": "vxlan0", "ipam":{"type":"host-local","ranges":[[{"subnet":"$subnet"}]],"dataDir":"/var/lib/cni/networks"}}
> "@
> 
>     $ipamConfig | Out-File "C:\k\sourceVipRequest.json"
> 
>     $env:CNI_COMMAND="ADD"
>     $env:CNI_CONTAINERID="dummy"
>     $env:CNI_NETNS="dummy"
>     $env:CNI_IFNAME="dummy"
>     $env:CNI_PATH="c:\k\cni" #path to host-local.exe
> 
>     If(!(Test-Path c:/k/sourceVip.json)){
>         Get-Content sourceVipRequest.json | .\cni\host-local.exe | Out-File sourceVip.json
>     }
> 
>     Remove-Item env:CNI_COMMAND
>     Remove-Item env:CNI_CONTAINERID
>     Remove-Item env:CNI_NETNS
>     Remove-Item env:CNI_IFNAME
>     Remove-Item env:CNI_PATH
> }
> ```
> 
> So I would suggest that we throw a copy of the file @jayunit100 shared (without the `Invoke-WebRequest ...`) into the `./Win` dir and call it in `k.ps1` instead of
> 
> ```
> GetSourceVip -ipAddress 10.0.0.10 -NetworkName $NetworkName
> ```

That did not fix the problem, so I am trying to really understand what is going on here. Unfortunately I have zero experience with powershell and I have to admit that until now I was only copy/pasting stuff I found on Google. But I will try my best:

The error says simply, that you can't index into an empty array, and even I understand that:
```
Cannot index into a null array.
At C:\k\helper.psm1:179 char:5
+     $subnet = $hnsNetwork.Subnets[0].AddressPrefix
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```
so let's look why it is empty. This function causes the error:

```
function GetSourceVip($ipaddress, $NetworkName)
{
...
    $hnsNetwork = Get-HnsNetwork | ? Name -EQ $NetworkName.ToLower()
    $subnet = $hnsNetwork.Subnets[0].AddressPrefix
...
}
```
where  `$hnsNetwork = Get-HnsNetwork | ? Name -EQ $NetworkName.ToLower()` is supposed to put values into it that then contains an array called `Subnets`. The command translates to "Get the `HnsNetwork` that has the name that is equal to `$NetworkName"`. `$NetworkName` is set in line 45 of `k.ps1`:
```
...
$NetworkName = "vxlan0"
...
```
And indeed if I run `Get-HnsNetwork` (after running `k.ps1`) there is no entry for `vxlan0`. 

`$NetworkName` is set up before the `install.ps1` is called, but (against my expectations) it is actually not passed as an argument:
```
powershell $install -NetworkMode "$NetworkMode" -clusterCIDR "$ClusterCIDR" -KubeDnsServiceIP "$KubeDnsServiceIP" -serviceCIDR "$ServiceCIDR" -InterfaceName "'$InterfaceName'" -LogDir "$LogDir"
```
But in `install.ps1` it is actually set to `"vxlan0"` if  the `$NetworkMode` is set to `"overlay"`.
```
$NetworkName = "cbr0"
if ($NetworkMode -eq "overlay")
{
    $NetworkName = "vxlan0"
}
```
And indeed, in `k.ps1` you find the line
```
$NetworkMode="overlay"
```
and is passed as a parameter to `install.ps1`, see above. So why is there no network with the name `"vxlan0"`? Further down at line 98 of `install.ps1` there are these lines:
```
# Prepare Network
ipmo C:\k\hns.psm1
CleanupOldNetwork $NetworkName
CreateExternalNetwork $NetworkMode
```
And `CleanupOldNetwork` seems to remove the network `vxlan0`-network. In the next line `CreateExternalNetwork` is called and when I tried out the `Get-HnsNetwork` command earlier, a network with the name `external` came up. So maybe this is just the network to be used.
Back to `k.ps1` I changed the  `$NetworkName`
```
$NetworkName = "external"
```
Now, when I run `k.ps1` (from a fresh new virtual machine) it runs without any errors. 
```
Status      : Running
Name        : kubelet
DisplayName : kubelet

Status      : Running
Name        : kube-proxy
DisplayName : kube-proxy
```
And if I ssh into master I get:
```
vagrant@master:~$ kubectl get nodes
NAME     STATUS   ROLES                  AGE   VERSION
master   Ready    control-plane,master   42m   v1.20.4
winw1    Ready    <none>                 33m   v1.20.4
```
It looks fine, but now I wonder if the `vxlan0`-network is actually important, and really what I just did I just obscured the error (for now). I will try to get some pods running later. Maybe now is a good time to try to execute `k.ps1` from the makefile.

**Comment by sladyn98** [comment] 2021-04-17 11:59
@FriedrichWilken Did you push this code to the k.ps1 ?

**Comment by FriedrichWilken** [comment] 2021-04-17 12:23
> @FriedrichWilken Did you push this code to the k.ps1 ?

now, sorry cleaned everything up first.

**Comment by FriedrichWilken** [comment] 2021-04-17 12:24
@sladyn98  let me know if this now works for you as well so I could close this issue.

**Comment by sladyn98** [comment] 2021-04-17 13:41
@FriedrichWilken  I tried it out but hitting this error

vagrant winrm -c "Restart-Computer" winw1
Failed to restart the computer vagrant with the following error message: The system shutdown cannot be initiated because there are other users logged on to the computer.
At line:1 char:1
+ Restart-Computer
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (vagrant:String) [Restart-Computer], InvalidOperationException
    + FullyQualifiedErrorId : RestartcomputerFailed,Microsoft.PowerShell.Commands.RestartComputerCommand
Makefile:2: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by FriedrichWilken** [comment] 2021-04-19 10:34
Looks like you are legged in the vm. This will prevent it from rebooting.

**Closed** 2021-04-19 14:54 UTC
